Feature/create list
chingu-voyage7/Geckos-Team-12 pull request #9
Opened 2018-12-21 20:34 UTC by joanclarke

2018-12-27 20:20 UTC, lgainsbrook requested changes
The first time the page loads, there's a bug where when you click "Add a list", the page reloads and you have to click it again. If this can be fixed quickly, I think we should do that before merging with development. 
The "Add another list" button also doesn't appear, but I'm not sure if it's supposed to or if that's your next step.

2018-12-27 21:26 UTC, joanclarke commented
Hmmm...that's weird, I am not seeing the issue to which you are referring.  When I click the 'Add a list' button, the form actually loads right away.  I also checked it using different browsers so I'm not sure how to fix that issue.  I have read that javascript has that issue sometimes though so I guess i can look into it. However, that will be done next week as (as I've mentioned in our meeting) I'm super busy this week. Also, please note that the 'Add another list' button only appears when you click on the close (x) button.  There are some issues with the 'Add a list/Add another list' link buttons but only as it pertains to which link appears whenever the close button is clicked and that depends on if a list has been created or not.  For example, if the user has already created a list when he/she clicks the close button, the 'Add another list' link should appear, otherwise, if he/she has not yet created a list and clicks the close button, the 'Add a list' will appear again. For now, only the 'Add another list' button appears when the close button is clicked. I will be working on that issue for my next step.

2018-12-29 00:45 UTC, lgainsbrook commented
Weird! I'll merge and we can figure it out later.

2018-12-29 00:45 UTC, lgainsbrook approved these changes

2018-12-29 00:45 UTC, merged